(()=>{'use strict';
const $=id=>document.getElementById(id),M={convoy:{title:'항로 결산',tag:'01 / RISK IS A RESOURCE',intro:'12턴 안에 물자 20개를 세 번 배송하세요. 욕심을 내면 위협이 쌓이고, 매 3턴 습격이 옵니다.',rules:'목표: 12턴 이내 물자20 배송 3회.\n안전 수집: 연료1 → 물자9, 위협+1. 위험 수집: 연료2 → 물자18, 위협+3.\n정비 항로: 연료+2, 물자+3, 위협-2. 배송: 물자20 소비, 연료+3, 선체+2, 위협-2.\n매3턴 위협-1-호위×2만큼 선체 피해(최소0), 이후 위협1 감소. 선체0 또는12턴까지 배송 미달이면 실패.\n호위/드론 투자도 1턴입니다. 시작 자원으로 비용과 습격 예고를 보고 선택하세요.'},fleet:{title:'편대 조율소',tag:'02 / READ THE ENEMY',intro:'공개된 적 3기와 장비 상성을 맞추세요. 6전투 중 4승을 거두고 선체를 보존하세요.',rules:'목표: 선체를 보존하며 6전투 중4승.\n왼쪽부터 적 장갑→절단◇, 반사→교란◎, 군집→산탄✦ 장비가 강합니다. 장비 버튼을 누르면 순환합니다.\n상성 일치 전투력6, 불일치2. 장비 강화당 기체별+1. 상대 방어는10에서 매전투2씩 증가.\n집중 사격: 에너지2, 전투력+4, 추가피해2. 엄호 전진: 에너지2, 피해3 감소. 절전 기동: 에너지2 회복, 전투력-2/추가피해1.\n승리하면 장비 강화 또는 선체3 회복을 선택합니다. 전투력 부족은 승점 없이 피해를 받습니다. 선체0이면 즉시 실패.'},colony:{title:'궤도 온실',tag:'03 / BUILD A LIVING ORBIT',intro:'태양 설비 옆에 온실을 놓으세요. 8교대 후 인구6 이상을 식량·전력과 함께 유지하면 성공합니다.',rules:'목표: 8교대 후 인구6 이상, 식량·전력 모두0 이상.\n중앙 본부는 전력2/식량2를 생산합니다. 태양 설비는전력3, 온실은식량2+직교 인접 태양마다1, 주거 모듈은인구2를 늘립니다.\n교대마다 인구만큼 식량, 인구÷2 올림만큼 전력을 소비합니다. 교대 후 합금3을 받습니다.\n태양/온실 비용합금5, 주거6. 매교대 시설1개 배치 가능, 철거 없음. 빈칸을 선택하고 시설 버튼을 누르세요.\n생활 연구: 합금6, 식량유지비1 감소(최대2). 연구도 이번교대 건설기회를 사용합니다. 자원 음수가 되면 즉시 실패. 배치 전에 다음교대 수지를 확인하세요.'}};
const key=new URLSearchParams(location.search).get('game'),mode=M[key]?key:'convoy',m=M[mode];document.body.dataset.mode=mode;document.title=m.title+' | 심다 LAB';$('title').textContent=m.title;$('intro').textContent=m.intro;$('eyebrow').textContent=m.tag;document.querySelectorAll('[data-mode]').forEach(a=>a.classList.toggle('active',a.dataset.mode===mode));let s=null,dialogKind='start',lastFocus=null;
function msg(t){$('notice').textContent=t;if(s){s.log.push(t);$('log').replaceChildren(...s.log.slice(-5).reverse().map(x=>{const li=document.createElement('li');li.textContent=x;return li}))}}
function modal(kind,title,text,button,cancel=false){dialogKind=kind;lastFocus=document.activeElement;$('dialogTag').textContent=m.tag;$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('primary').textContent=button;$('cancel').hidden=!cancel;if(!$('dialog').open)$('dialog').showModal();$('primary').focus()}
function close(){ $('dialog').close();lastFocus?.focus() }
function start(){s={status:'play',log:[],turn:0,hull:10,fuel:8,cargo:0,threat:0,done:0,shield:0,drone:0,energy:6,gear:[0,0,0],wins:0,power:0,grid:Array(9).fill(null),tile:null,metal:10,food:12,electric:10,pop:2,built:false,study:0};s.grid[4]='core';if(mode==='fleet')s.hull=12;close();render();msg('작전 시작. '+m.intro);$('actions').querySelector('button')?.focus()}
function finish(win){const reason=win?'':mode==='convoy'?(s.hull<=0?'선체 소진. 습격 직전 배송/정비 또는 호위 투자를 활용하세요.':'배송 기한 초과. 남은 턴에 물자20을 세 번 배송해야 합니다.'):mode==='fleet'?(s.hull<=0?'선체 소진. 상성 일치·엄호·승리 후 회복을 함께 활용하세요.':'승리 목표 미달. 전투 전 상성과 예상 전투력을 확인하세요.'):(s.food<0?'식량 부족. 온실 인접 생산 또는 생활 연구로 유지비를 줄이세요.':s.electric<0?'전력 부족. 주거 확장 전에 태양 설비를 확보하세요.':'인구 목표 미달. 주거 모듈 두 개로 인구6을 확보하세요.');s.status=win?'won':'lost';render();modal('result',win?'작전 성공':'작전 실패',mode==='convoy'?`배송 ${s.done}/3 · ${s.turn}/12턴 · 선체 ${s.hull}/10`:mode==='fleet'?`${s.wins}승(목표4) · ${s.turn}/6전투 · 선체 ${s.hull}/12`:`${s.turn}/8교대 · 인구 ${s.pop}/6 · 식량 ${s.food} · 전력 ${s.electric}`,'다시 시작');if(reason)$('dialogText').textContent+='\n\n'+reason;}
$('primary').onclick=()=>{if(['start','result','restart'].includes(dialogKind))start();else close()};$('cancel').onclick=close;$('dialog').addEventListener('cancel',e=>{if(['start','result'].includes(dialogKind))e.preventDefault()});$('restart').onclick=()=>modal('restart','처음부터 시작할까요?','현재 판의 진행은 초기화됩니다. 취소하면 현재 판으로 돌아갑니다.','새 판 시작',true);$('rules').onclick=()=>modal('rules','작전 규칙',m.rules,'현재 판으로 돌아가기');
function button(title,desc,fn,cls='',disabled=false){const b=document.createElement('button'),strong=document.createElement('span'),small=document.createElement('small');strong.textContent=title;small.textContent=desc;b.append(strong,small);b.onclick=fn;b.className=cls;b.dataset.action=title;b.disabled=disabled;$('actions').append(b);return b}
function meter(label,value){const e=document.createElement('div');e.className='meter';const a=document.createElement('small'),b=document.createElement('strong');a.textContent=label;b.textContent=value;e.append(a,b);$('meters').append(e)}
function segment(text){const h=document.createElement('p');h.className='subheading';h.textContent=text;$('actions').append(h)}
function action(fn){if(!s||s.status!=='play'||$('dialog').open)return;const tag=document.activeElement?.dataset.action;fn();render();if(s.status==='play'&&!$('dialog').open&&tag)Array.from(document.querySelectorAll('button[data-action]')).find(b=>b.dataset.action===tag)?.focus()}
function convoyPreview(delta,extraShield=0){return (s.turn+1)%3===0?' · 이번 습격피해'+Math.max(0,Math.max(0,s.threat+delta)-1-(s.shield+extraShield)*2):''}
function convoy(kind){action(()=>{if(kind==='safe'||kind==='risk'){const cost=kind==='safe'?1:2;if(s.fuel<cost){msg('연료 부족. 정비 항로로 연료를 회복하세요.');return}s.fuel-=cost;s.cargo+=(kind==='safe'?9:18)+s.drone*2;s.threat+=kind==='safe'?1:3;msg((kind==='safe'?'안전':'위험')+' 수집 · 물자 '+s.cargo+', 위협 '+s.threat)}if(kind==='rest'){s.fuel=Math.min(12,s.fuel+2);s.cargo+=3;s.threat=Math.max(0,s.threat-2);msg('정비 항로 · 연료/물자 회복, 위협 감소')}if(kind==='deliver'){if(s.cargo<20){msg('배송 물자 부족: 20개 필요. 현재 '+s.cargo+'개.');return}s.cargo-=20;s.done++;s.fuel=Math.min(12,s.fuel+3);s.hull=Math.min(10,s.hull+2);s.threat=Math.max(0,s.threat-2);msg('배송 '+s.done+'/3 · 물자20 소비, 선체/연료 회복')}if(kind==='shield'||kind==='drone'){const cost=kind==='shield'?10:8;if(s.cargo<cost){msg('성장 비용 부족: 물자'+cost+'개 필요.');return}if(s[kind]>=2){msg('이 성장의 최대 레벨입니다.');return}s.cargo-=cost;s[kind]++;msg((kind==='shield'?'호위':'수집 드론')+' 성장 '+s[kind])}s.turn++;if(s.turn%3===0){const dmg=Math.max(0,s.threat-1-s.shield*2);s.hull=Math.max(0,s.hull-dmg);s.threat=Math.max(0,s.threat-1);msg('턴'+s.turn+' 습격 · 선체 피해'+dmg)}if(s.hull<=0)finish(false);else if(s.done>=3)finish(true);else if(s.turn>=12)finish(false)})}
const enemyPattern=[[0,1,2],[1,2,0],[2,0,1],[0,2,1],[1,0,2],[2,1,0]],weapons=['절단 ◇','교란 ◎','산탄 ✦'],types=['장갑 □','반사 ◎','군집 ⋮'];
function fleetPreview(stance){const enemy=enemyPattern[Math.min(s.turn,5)],match=s.gear.filter((g,i)=>g===enemy[i]).length,power=match*6+(3-match)*2+s.power*3+(stance==='focus'?4:stance==='eco'?-2:0),win=power>=10+s.turn*2,dmg=Math.max(1,(win?s.turn+2:s.turn+4)-s.shield+(stance==='focus'?2:stance==='guard'?-3:1));return ' · 예상 '+(win?'승리':'불리')+'/피해'+dmg}
function fleet(stance){action(()=>{const cost=stance==='focus'?2:stance==='guard'?2:0;if(s.energy<cost){msg('에너지 부족. 절전 기동으로 회복하세요.');return}s.energy-=cost;if(stance==='eco')s.energy=Math.min(8,s.energy+2);const enemy=enemyPattern[Math.min(s.turn,5)],match=s.gear.filter((g,i)=>g===enemy[i]).length;const attack=match*6+(3-match)*2+s.power*3+(stance==='focus'?4:stance==='eco'?-2:0),defense=10+s.turn*2,win=attack>=defense;const damage=Math.max(1,(win?s.turn+2:s.turn+4)-s.shield+(stance==='focus'?2:stance==='guard'?-3:1));s.hull=Math.max(0,s.hull-damage);s.turn++;if(win)s.wins++;msg(`전투${s.turn} ${win?'승리':'불리'} · 상성${match}/3 · 전투력${attack}/${defense} · 선체피해${damage}`);if(s.hull<=0){finish(false);return}if(s.turn>=6){finish(s.wins>=4);return}if(win){s.status='upgrade';render();msg('승리 보상: 장비 강화 또는 선체 회복을 선택하세요.')}})}
function growth(kind){if(s?.status!=='upgrade')return;if(kind==='power')s.power++;else s.hull=Math.min(12,s.hull+3);s.status='play';render();msg(kind==='power'?'세 기체 장비 전투력+1':'선체3 회복');$('actions').querySelector('button')?.focus()}
const facility={core:{icon:'⌂',name:'본부'},sun:{icon:'☀',name:'태양 설비'},farm:{icon:'♧',name:'온실'},home:{icon:'▣',name:'주거 모듈'}};
function adjacent(i){const n=[];if(i%3>0)n.push(i-1);if(i%3<2)n.push(i+1);if(i>2)n.push(i-3);if(i<6)n.push(i+3);return n}
function yieldColony(){let food=2,power=2;for(let i=0;i<9;i++){if(s.grid[i]==='sun')power+=3;if(s.grid[i]==='farm')food+=2+adjacent(i).filter(j=>s.grid[j]==='sun').length}return {food,power,foodUse:Math.max(0,s.pop-s.study),powerUse:Math.ceil(s.pop/2)}}
function build(kind){action(()=>{if(s.built){msg('이번 교대 건설을 마쳤습니다. 교대를 진행하세요.');return}if(kind==='study'){if(s.study>=2){msg('생활 연구는 최대2레벨입니다.');return}if(s.metal<6){msg('연구 합금6이 필요합니다.');return}s.metal-=6;s.study++;s.built=true;msg('생활 연구 '+s.study+' · 식량 유지비 감소');return}if(s.tile===null||s.grid[s.tile]){msg('먼저 비어 있는 칸을 선택하세요.');return}const cost=kind==='home'?6:5;if(s.metal<cost){msg('합금 부족: '+cost+'개 필요. 다음 교대 보상은3개입니다.');return}s.metal-=cost;s.grid[s.tile]=kind;if(kind==='home')s.pop+=2;s.built=true;msg((s.tile+1)+'번칸 '+facility[kind].name+' 설치');s.tile=null})}
function shift(){action(()=>{const y=yieldColony();s.food+=y.food-y.foodUse;s.electric+=y.power-y.powerUse;s.metal+=3;s.turn++;s.built=false;msg(`교대${s.turn} · 식량 ${y.food-y.foodUse>=0?'+':''}${y.food-y.foodUse}, 전력 ${y.power-y.powerUse>=0?'+':''}${y.power-y.powerUse}, 합금+3`);if(s.food<0||s.electric<0)finish(false);else if(s.turn>=8)finish(s.pop>=6)})}
function render(){if(!s)return;$('meters').replaceChildren();$('actions').replaceChildren();$('scene').replaceChildren();$('phase').textContent=s.status==='upgrade'?'성장 선택 중':s.status==='play'?'작전 진행 중':'작전 종료';$('help').textContent='규칙 보기는 진행을 보존합니다. Tab/Enter로 모든 선택을 조작할 수 있습니다.';
 if(mode==='convoy'){meter('배송 / 제한턴',`${s.done}/3 · ${s.turn}/12`);meter('선체',s.hull+'/10');meter('연료',s.fuel+'/12');meter('물자 / 위협',s.cargo+' / '+s.threat);$('sceneTitle').textContent='TRADE LANE / 수집 → 배송';const orbit=document.createElement('div');orbit.className='orbit';orbit.innerHTML='<div><div class="orb">◌</div><small>잔해 지대</small></div><div><div class="ship">➤</div><small>구조 운송선 · 호위 '+s.shield+' / 드론 '+s.drone+'</small></div><div><div class="orb">⌂</div><small>구조 기지</small></div>';$('scene').append(orbit);const bar=document.createElement('div');bar.className='cargo-bar';bar.innerHTML='<span style="width:'+Math.min(100,s.cargo/20*100)+'%"></span>';$('scene').append(bar);const text=document.createElement('p');text.className='yield';text.textContent='배송20 필요 · 현재 '+s.cargo+' · 다음 배송 후 선체+2/연료+3';$('scene').append(text);const left=3-s.turn%3;$('forecast').textContent='다음 습격 '+left+'턴 후 · 현재 위협 기준 피해 '+Math.max(0,s.threat-1-s.shield*2)+' · 배송/정비는 위협2 감소';$('guide').textContent='배송을 세 번 마치세요. 모든 유효 행동은1턴, 부족한 비용의 선택은 자원과 턴을 소비하지 않습니다.';button('안전 수집','연료1 · 물자'+(9+s.drone*2)+' · 위협+1'+convoyPreview(1),()=>convoy('safe'));button('위험 수집','연료2 · 물자'+(18+s.drone*2)+' · 위협+3'+convoyPreview(3),()=>convoy('risk'));button('정비 항로','연료+2 · 물자+3 · 위협-2'+convoyPreview(-2),()=>convoy('rest'));button('물자 배송','물자20 · 선체+2 · 연료+3'+convoyPreview(-2),()=>convoy('deliver'),'main-action');segment('성장 투자 · 1턴 사용');button('호위 증설','물자10 · 습격피해-2 · '+s.shield+'/2',()=>convoy('shield'));button('수집 드론','물자8 · 수집물자+2 · '+s.drone+'/2',()=>convoy('drone'));}
 if(mode==='fleet'){meter('승리 / 전투',`${s.wins}승 · ${s.turn}/6`);meter('선체',s.hull+'/12');meter('에너지',s.energy+'/8');meter('장비 강화',s.power+'단계');$('sceneTitle').textContent='FLEET MATCH / 적을 읽고 대응';const enemy=enemyPattern[Math.min(s.turn,5)];for(const kind of ['enemy','ours']){if(kind==='ours'){const t=document.createElement('div');t.className='versus';t.textContent='VS / 선체 격벽 '+s.shield;$('scene').append(t)}const form=document.createElement('div');form.className='formation';for(let i=0;i<3;i++){const d=document.createElement('div');d.className='vessel';const b=document.createElement('b'),t=document.createElement('small');b.textContent=(kind==='enemy'?types[enemy[i]]:weapons[s.gear[i]]).split(' ')[1];t.textContent=(i+1)+'번 '+(kind==='enemy'?types[enemy[i]]:weapons[s.gear[i]]);d.append(b,t);form.append(d)}$('scene').append(form)}const match=s.gear.filter((g,i)=>g===enemy[i]).length;$('forecast').textContent=(s.turn>=6?'최종 적 방어 ':'다음 적 방어 ')+(10+Math.min(s.turn,5)*2)+' · 상성 '+match+'/3 · 기본 전투력 '+(match*6+(3-match)*2+s.power*3)+' · 절단→장갑 / 교란→반사 / 산탄→군집';$('guide').textContent=s.status==='upgrade'?'성장 보상을 하나 선택하면 다음 적 편성이 공개됩니다.':'기체 버튼을 눌러 장비를 순환한 뒤 전술로 전투하세요. 배치는 턴/에너지를 소비하지 않습니다.';if(s.status==='upgrade'){button('장비 강화','세 기체 전투력 각각+1',()=>growth('power'),'main-action');button('선체 회복','선체3 회복 · 최대12',()=>growth('repair'));}else{const load=document.createElement('div');load.className='loadout';for(let i=0;i<3;i++){const b=document.createElement('button');b.textContent=(i+1)+'번 기체 '+weapons[s.gear[i]];b.dataset.action='gear-'+i;b.onclick=()=>action(()=>{s.gear[i]=(s.gear[i]+1)%3;msg((i+1)+'번 기체 '+weapons[s.gear[i]]+' 선택')});load.append(b)}$('actions').append(load);button('집중 사격','에너지2 · 전투력+4'+fleetPreview('focus'),()=>fleet('focus'));button('엄호 전진','에너지2 · 선체피해-3'+fleetPreview('guard'),()=>fleet('guard'),'main-action');button('절전 기동','에너지+2 · 전투력-2'+fleetPreview('eco'),()=>fleet('eco'));}}
 if(mode==='colony'){meter('인구 / 교대',s.pop+'/6 · '+s.turn+'/8');meter('식량',s.food);meter('전력',s.electric);meter('합금',s.metal);$('sceneTitle').textContent='ORBITAL GRID / 공간이 생산을 바꿉니다';const grid=document.createElement('div');grid.className='grid';for(let i=0;i<9;i++){const b=document.createElement('button');b.className='tile';b.dataset.action='tile-'+i;b.setAttribute('aria-pressed',String(s.tile===i));const f=s.grid[i]?facility[s.grid[i]]:null;b.setAttribute('aria-label',(i+1)+'번칸 '+(f?f.name:'빈칸'));const icon=document.createElement('b'),label=document.createElement('span');icon.textContent=f?f.icon:'+';label.textContent=(i+1)+' · '+(f?f.name:'빈칸');b.append(icon,label);b.onclick=()=>action(()=>{s.tile=i;msg(f?'이미 설치된 시설입니다. 빈칸을 선택하세요.':(i+1)+'번 빈칸 선택 · 시설을 설치하세요.')});grid.append(b)}$('scene').append(grid);const y=yieldColony();$('forecast').textContent=`다음 교대 식량 ${y.food}생산-${y.foodUse}소비=${y.food-y.foodUse>=0?'+':''}${y.food-y.foodUse}, 전력 ${y.power}생산-${y.powerUse}소비=${y.power-y.powerUse>=0?'+':''}${y.power-y.powerUse} · 생활 연구${s.study}/2`;$('guide').textContent='빈칸 선택→시설 배치→교대 진행. 태양 바로 위/아래/좌/우의 온실은 추가 생산합니다. '+(s.built?'이번 건설 완료.':'이번 교대 건설 가능.')+(s.tile!==null?' 선택칸 '+(s.tile+1)+'.':'');button('태양 설비 설치','합금5 · 전력+3/교대',()=>build('sun'));button('온실 설치','합금5 · 식량'+(2+(s.tile!==null?adjacent(s.tile).filter(j=>s.grid[j]==='sun').length:0))+'/교대'+(s.tile===null?' · 칸 선택 필요':''),()=>build('farm'));button('주거 모듈 설치','합금6 · 인구+2/소비 증가',()=>build('home'));button('생활 연구','합금6 · 식량유지비-1',()=>build('study'));button('교대 진행','생산/소비 정산 · 합금+3',shift,'main-action');}
 if(s.status==='won'||s.status==='lost')$('actions').querySelectorAll('button').forEach(b=>b.disabled=true);
}
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&s&&['won','lost'].includes(s.status)){e.preventDefault();start()}});modal('start',m.title,m.rules,'시작하기');
})();
